[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp3{9,10}-*"
before-build = "yum install -y openssl-devel || apk add openssl-dev"

[tool.cibuildwheel.linux]
archs = ["auto", "aarch64"]
