[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pykdeconnect"
version = "0.1.2a1"
requires-python = ">=3.9"
authors = [{ name = "Adrian Freund", email = "adrian@freund.io" }]
description = "A python implementation of the kdeconnect protocol"
keywords = ["kde", "connect"]
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Utilities",
    "Typing :: Typed",
]

dependencies = [
    "cryptography>=35.0.0,<37.0",
    "typing_extensions>=4.1.1,<5.0",
    "voluptuous>=0.12.2,<0.13",
]

[dependency-groups]
dev = [
    {include-group = "tox"},
    {include-group = "pre-commit"},
    {include-group = "lint"},
    {include-group = "type-check"},
    {include-group = "test"},
]
pre-commit = [
    "pre-commit",
]
tox = [
    "tox",
    "tox-uv",
]
lint = [
    "flake8",
    "isort",
]
type-check = [
    "mypy==0.941",
]
test = [
    "pytest",
    "pytest-asyncio>=0.17",
    "pytest-cov",
    {include-group = "coverage"},
]
coverage = [
    "coverage[toml]",
]

[tool.setuptools.packages.find]

[tool.setuptools.package-data]
pykdeconnect = ["py.typed"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "strict"

[tool.isort]
multi_line_output = 5
src_paths = ["pykdeconnect", "tests"]

[tool.mypy]
show_error_codes = true
strict = true
warn_unreachable = true
files = ["pykdeconnect"]

[tool.coverage.run]
source = ["pykdeconnect"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "assert False"
]

