[tox]
envlist = clean, py39, py310, lint, {py39,py310}-typing, report

[testenv]
runner = uv-venv-lock-runner
no_default_groups = true
depends =
    {py39,py310}: clean
    report: py39,py310

[testenv:{py39,py310}]
dependency_groups = test
commands = pytest --cov --cov-append --cov-report=

[testenv:report]
only_groups = coverage
skip_install = true
commands = coverage report

[testenv:clean]
only_groups = coverage
skip_install = true
commands = coverage erase

[testenv:lint]
only_groups = lint
commands =
    isort --check-only src/pykdeconnect tests
    flake8 src/pykdeconnect

[testenv:{py39,py310}-typing]
dependency_groups = type-check
commands = mypy src/pykdeconnect
