[tox]
envlist = clean, py39, py310, lint, {py39,py310}-typing, report

[testenv]
only_groups = test
commands = pytest --cov --cov-append --cov-report=
depends =
    {py39,py310}: clean
    report: py39,py310

[testenv:report]
only_groups = coverage
skip_install = true
commands = coverage report

[testenv:clean]
only_groups = coverage
skip_install = true
commands = coverage erase

[testenv:lint]
only_groups = lint
commands =
    isort --check-only pykdeconnect tests
    flake8 pykdeconnect

[testenv:{py39,py310}-typing]
only_groups = type-checking
commands = mypy pykdeconnect
