# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**/*.rst'
      - .gitignore
  release:
    types:
      - published

jobs:
  make_sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install build

    - name: Build package
      run: python -m build --sdist

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*.tar.gz

# We don't build wheels because of problems with linking OpenSSL
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Build wheels (Linux)
        uses: pypa/cibuildwheel@v2.3.1
        if: runner.os == 'Linux'
        env:
          CIBW_BUILD: cp3{9,10}-*
          CIBW_ARCHS_LINUX: "auto aarch64"
          CIBW_BEFORE_BUILD: yum install -y openssl-devel || apt install -y libssl-dev

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  upload_all:
    needs: [make_sdist, build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
